<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>HerrGeneral.Testing</RootNamespace>
        <AssemblyName>HerrGeneral.Testing</AssemblyName>
    </PropertyGroup>
    
    <PropertyGroup>
        <IsPackable>true</IsPackable>
        <Title>Herr General</Title>
        <Authors>Codeve Soft</Authors>
        <MinVerTagPrefix>v</MinVerTagPrefix>
        <Copyright>Copyright (c) CODEVE SOFT 2026</Copyright>
        <Product>Herr General</Product>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
        <EnablePackageValidation>true</EnablePackageValidation>
        
        <Description>Testing utilities and fluent assertion extensions for HerrGeneral CQRS applications</Description>
        <PackageTags>HerrGeneral;Test;Testing;Assertions</PackageTags>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Divergic.Logging.Xunit"/>
        <PackageReference Include="Shouldly"/>
        <PackageReference Include="xunit.assert"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="MinVer">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.SourceLink.GitHub">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>
    
    <ItemGroup>
      <ProjectReference Include="..\HerrGeneral.Core\HerrGeneral.Core.csproj" />
      <ProjectReference Include="..\HerrGeneral.Primitives\HerrGeneral.Primitives.csproj" />
    </ItemGroup>
    
    <ItemGroup>
        <None Include="README.md" Pack="true" PackagePath="\" />
    </ItemGroup>
</Project>
