<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="OpenTelemetry"/>
        <PackageReference Include="OpenTelemetry.Exporter.InMemory"/>
        <PackageReference Include="FakeItEasy"/>
        <PackageReference Include="Microsoft.Extensions.Logging.Console"/>
        <PackageReference Include="Microsoft.Extensions.Logging.Debug"/>
        <PackageReference Include="Microsoft.NET.Test.Sdk"/>
        <PackageReference Include="Shouldly"/>
        <PackageReference Include="xunit"/>
        <PackageReference Include="xunit.runner.visualstudio">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="coverlet.collector">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\src\HerrGeneral.OpenTelemetry\HerrGeneral.OpenTelemetry.csproj" />
      <ProjectReference Include="..\..\src\HerrGeneral.Test.Extension\HerrGeneral.Test.Extension.csproj" />
      <ProjectReference Include="..\..\src\HerrGeneral.Core\HerrGeneral.Core.csproj" />
      <ProjectReference Include="..\..\src\HerrGeneral.WriteSide\HerrGeneral.WriteSide.csproj" />
    </ItemGroup>

</Project>
